#!/usr/bin/env bash

source ~/vboxmanage.conf
#username=security
#host=172.17.0.1

# place somewhere and link somewhere
# cd /usr/local/bin
# ln -s this.sh vboxmanage

echo ssh ${username}@${host} $(basename $0) $@
ssh ${username}@${host} $(basename $0) $@

#for use with bindshell
#echo $(basename $0) $@ | nc ${host} 4444
#echo "vboxmanage $@" | nc ${host} 4444
