#!/usr/bin/env bash

source ~/vboxmanage.conf
#username=security
#host=172.17.0.1

# place somewhere and link somewhere
# cd /usr/local/bin
# ln -s this.sh vboxmanage

# ssh connects stdin to stdin of the remote command thereby consuming all stdin.
# -n doesn't forward stdin to the remote command. Potentially breaking
# "modifyvm [--teleporterpasswordfile <file>|stdin]" and
# "convertfromraw stdin <outputfile> <bytes>"
if [[ "$method" == "ssh" ]]
then
  echo ssh -n ${username}@${host} $(basename $0) $@
  ssh -n ${username}@${host} $(basename $0) $@
fi

#for use with bindshell
if [[ "$method" == "vboxmanageapi" ]]
then
  echo $(basename $0) $@ \| nc ${host} 4444
  echo -n "vboxmanage $@" | nc ${host} 4444
fi
