# Default values for rspamd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/michaelweiser/peekabooav-rspamd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# modules to enable, all others are disabled.
modules:
  - external_services
  - force_actions

debug:
  # echo generated configuration at end of rspamd container entrypoint for
  # diagnostics
  config: false

config: {}
# rspamd configuration object tree, example:
#  options:
#    filters: ""
#  external_services:
#    peekaboo:
#      servers: "peekabooav"
#      min_size: 50
#    # Timeout call for some delay at main stage
#    dcc:
#      servers: "240.0.0.1"
#      min_size: 50
#      timeout: 2
#  group:
#    antivirus:
#      symbols:
#        PEEKABOO:
#          weight: 4.0
#          description_: "The Peekaboo analysis found a threat"
#          groups:
#          - "peekaboo"
#          - "av_virus_reject"
#          one_shot: true
#        PEEKABOO_FAIL:
#          weight: 0
#          description: "The Peekaboo analysis failed"
#          groups:
#          - "peekaboo"
#          - "av_scanner_failed"
#          one_shot: true
#        PEEKABOO_IN_PROCESS:
#          weight: 0
#          description: "The Peekaboo analysis was not finished"
#          groups:
#          - "peekaboo"
#          one_shot: true
#  force_actions:
#    rules:
#      PEEKABOO_IN_PROCESS:
#        action: "soft reject"
#        message: "SOFT REJECT"
#        expression: "PEEKABOO_IN_PROCESS"
#        honor_action:
#        - "reject"
#      PEEKABOO:
#        action: "reject"
#        message: "REJECT"
#        expression: "PEEKABOO"
#        require_action:
#        - "no action"
#        - "greylist"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 11332

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
